// <auto-generated />
namespace Videously.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EnforceMembershipTypeName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnforceMembershipTypeName));
        
        string IMigrationMetadata.Id
        {
            get { return "202210071409042_EnforceMembershipTypeName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
